### ISSUE TITLE
Some ACM failing. 500 error

### ISSUE THREAD

**Issue by keithkade** [ecologylab/BigSemanticsService#17]
examples

http://ecology-service.cse.tamu.edu/BigSemanticsService/metadata.jsonp?callback=storeNodeMD&url=http%3A%2F%2Fdl.acm.org%2FASIA%2520CCS%2520%2714

and

http://dl.acm.org/citation.cfm?id=1242672

**Comment by quyin** [comment]
for the first one, what's the correct URL? I seem to get 404 from that ACM page.

for the second one, it should be working now.

there is an out of memory issue though, so the service went unresponsive after some amount of requests. I'm looking into the problem.

**Comment by keithkade** [comment]
I lost track of the URL for the first one. 

Here is another URL that is failing though: http://dl.acm.org/citation.cfm?id=2557083
